## code to prepare `pres_el1960` dataset goes here

# loading package
devtools::load_all(".")

# importing and organizing data
pres_el1960 <- read.csv("data-raw/pres_el1960.csv", encoding = "Latin-1") %>%
  as_tibble() %>%
  rename(name_mun = municip_name) %>%
  mutate(name_mun = stringr::str_to_lower(name_mun),
         name_mun = stringr::str_replace_all(name_mun, "-", " "),
         name_mun = stringi::stri_trans_general(name_mun, "Latin-ASCII")
  )  %>%
  distinct(state_mun, .keep_all = T) %>%
  mutate(name_mun = str_squish(name_mun)) %>%
  mutate(name_mun = case_when(
  state_mun == "GoiasALOAND1A" ~ "aloandia",
  state_mun == "GoiasANHAGUERA" ~ "anhanguera",
  state_mun == "CearaARACOAIBA" ~ "aracoiaba",
  state_mun == "Minas GeraisABETE" ~ "abaete",
  state_mun == "Santa CatarinaARAGUARI" ~ "araquari",
  state_mun == "PernambucoARCO VERDE" ~ "arcoverde",
  state_mun == "Rio Grande do NorteACRCIA BRANCA" ~ "areia branca",
  state_mun == "Rio Grande do NorteAREZ" ~ "ares",
  state_mun == "Rio Grande do NorteASSU" ~ "acu",
  state_mun == "Sao PauloARTHUR NOGUEIRA" ~ "artur nogueira",
  state_mun == "Sao PauloATIBIA" ~ "atibaia",
  state_mun == "AmazonasALTAZES" ~ "autazes",
  state_mun == "BahiaBARRA  OA  ESTIVA" ~ "barra da estiva",
  state_mun == "Mato GrossoBATAGUACU" ~ "bataguassu",
  state_mun == "PernambucoBELEM DO SAO FRANCISCO" ~ "belem de sao francisco",
  state_mun == "Rio de JaneiroBON  JESUS  DO  ITABAPOANA" ~ "bom jesus do itabapoana",
  state_mun == "Sao PauloBOM JESUS DOS PEODOES" ~ "bom jesus dos perdoes",
  state_mun == "Minas GeraisBOMFIM" ~ "bonfim",
  state_mun == "GoiasBRASILANIA" ~ "brasilandia",
  state_mun == "Minas GeraisBRAZOPOLIS" ~ "brasopolis",
  state_mun == "GoiasBRASABRANTES" ~ "brazabrantes",
  state_mun == "Sao PauloBRODOSQUE" ~ "brodosqui",
  state_mun == "Rio de JaneiroCACHOEIRA DE MACACU" ~ "cachoeiras de macacu",
  state_mun == "Espirito SantoCACHOAIRO DE  ITAPEMIRIM" ~ "cachoeiro de itapemirim",
  state_mun == "GoiasCAMPO ALEGRE  OE  GOIAS" ~ "campo alegre de goias",
  state_mun == "SergipeCAMPO DE BRITO" ~ "campo do brito",
  state_mun == "BahiaCAR1NHANHA" ~ "carinhanha",
  state_mun == "Rio de JaneiroCASEMIRO DE ABREU" ~ "casimiro de abreu",
  state_mun == "Sao PauloCASSIA DOS COQUERIOS" ~ "cassia dos coqueiros",
  state_mun == "Rio Grande do SulCAZIAS DO SUL" ~ "caxias do sul",
  state_mun == "Sao PauloCHARQUEDA" ~ "charqueada",
  state_mun == "Sao PauloXAVANTES" ~ "chavantes",
  state_mun == "BahiaCHORROCHN" ~ "chorrocho",
  state_mun == "BahiaCONCEICAD DA FEIRA" ~ "conceicao da feira",
  state_mun == "PiauiCONCEICAO DE CANINDE" ~ "conceicao do caninde",
  state_mun == "Minas GeraisCORAÇAO JESUS" ~ "coracao de jesus",
  state_mun == "Sao PauloCUTIA" ~ "cotia",
  state_mun == "GoiasCRISTIANDPOLIS" ~ "cristianopolis",
  state_mun == "Santa CatarinaDESCANO" ~ "descanso",
  state_mun == "Minas GeraisDESTERRO DE ENTRE DOIS" ~ "desterro de entre rios",
  state_mun == "AlagoasDOTS RIACHOS" ~ "dois riachos",
  state_mun == "AmazonasEIRUREPE" ~ "eirunepe",
  state_mun == "PiauiETESBAO VELOSO" ~ "elesbao veloso",
  state_mun == "Rio Grande do SulENEANTADO" ~ "encantado",
  state_mun == "Rio Grande do SulENERUZILHADA DO SUL" ~ "encruzilhada do sul",
  state_mun == "Rio de JaneiroENGENHEIRO  PAULO  DE  FRONTIM" ~ "engenheiro paulo de frontin",
  state_mun == "Rio Grande do SulEREXIM" ~ "erechim",
  state_mun == "Rio Grande do SulERVAL DO SUL" ~ "erval",
  state_mun == "PernambucoESCADOR" ~ "escada",
  state_mun == "Rio Grande do SulESTENCIA VELHA" ~ "estancia velha",
  state_mun == "Santa CatarinaFACHINAL DOS GUEDES" ~ "faxinal dos guedes",
  state_mun == "Rio Grande do SulFELIX" ~ "feliz",
  state_mun == "ParanaFLORAL" ~ "florai",
  state_mun == "ParanaFOZ DO IGUAELI" ~ "foz do iguacu",
  state_mun == "Rio Grande do SulFREDERICO WESTPHALEA" ~ "frederico westphalen",
  state_mun == "Sao PauloGABRIEL MONTERO" ~ "gabriel monteiro",
  state_mun == "Rio Grande do SulGUARAMA" ~ "gaurama",
  state_mun == "GoiasGOIANOPOLIS" ~ "goianapolis",
  state_mun == "ParanaGOIO ERE" ~ "goioere",
  state_mun == "SergipeGRACKO CARDOSO" ~ "gracho cardoso",
  state_mun == "Espirito SantoGUANCUI" ~ "guacui",
  state_mun == "Sao PauloGUAPIRA" ~ "guapiara",
  state_mun == "ParaibaGUABIRA" ~ "guarabira",
  state_mun == "CearaGUARACIBA DO NORTE" ~ "guaraciaba do norte",
  state_mun == "Sao PauloGUARATA" ~ "guaranta",
  state_mun == "Sao PauloGUARAJA" ~ "guaruja",
  state_mun == "AlagoasIPACI" ~ "igaci",
  state_mun == "Rio Grande do SulIPUI" ~ "ijui",
  state_mun == "Minas GeraisILICENEA" ~ "ilicinea",
  state_mun == "Santa CatarinaINMITUBA" ~ "imbituba",
  state_mun == "PiauiINHUMAS" ~ "inhuma",
  state_mun == "Rio Grande do NorteIPANGUASSU" ~ "ipanguacu",
  state_mun == "CearaIRACEMO" ~ "iracema",
  state_mun == "ParanaITAGUAIE" ~ "itaguaje",
  state_mun == "PiauiITAMPOLIS" ~ "itainopolis",
  state_mun == "Santa CatarinaITAJA" ~ "itajai",
  state_mun == "Minas GeraisITAPAGIBE" ~ "itapagipe",
  state_mun == "Minas GeraisITAPECERIC" ~ "itapecerica",
  state_mun == "CearaITAPIROCA" ~ "itapipoca",
  state_mun == "Sao PauloITAQUAQUICETUBA" ~ "itaquaquecetuba",
  state_mun == "GoiasITAMBIARA" ~ "itumbiara",
  state_mun == "Santa CatarinaITAPORANGA" ~ "ituporanga",
  state_mun == "Sao PauloITUPERAVA" ~ "ituverava",
  state_mun == "PernambucoJABOATAO" ~ "jaboatao dos guararapes",
  state_mun == "ParanaJACARESINHO" ~ "jacarezinho",
  state_mun == "Minas GeraisJAGUARUÇU" ~ "jaguaracu",
  state_mun == "CearaJAGUARANA" ~ "jaguaruana",
  state_mun == "Santa CatarinaJAGUARUMA" ~ "jaguaruna",
  state_mun == "PiauiJOROMENHA" ~ "jerumenha",
  state_mun == "Minas GeraisJODAIMA" ~ "joaima",
  state_mun == "Rio Grande do NorteJOSE DE PENHA" ~ "jose da penha",
  state_mun == "AmazonasJUTAL" ~ "jutai",
  state_mun == "MaranhaoLOGO DA PEDRA" ~ "lago da pedra",
  state_mun == "Rio Grande do SulLAGOA VERMELBA" ~ "lagoa vermelha",
  state_mun == "PernambucoLAGEADO" ~ "lajedo",
  state_mun == "Rio Grande do NorteLAGES" ~ "lajes",
  state_mun == "Rio Grande do NorteLAGOS PINTADA" ~ "lajes pintadas",
  state_mun == "PiauiLANDRY SALES" ~ "landri sales",
  state_mun == "PernambucoLIMONEIRO" ~ "limoeiro",
  state_mun == "BahiaLIVRAMENTO DO BRUMADO" ~ "livramento",
  state_mun == "Sao PauloLUIZ ANTONIO" ~ "luis antonio",
  state_mun == "Rio Grande do NorteLUIZ GOMEZ" ~ "luis gomes",
  state_mun == "PiauiLUIZ CORREIA" ~ "luis correia",
  state_mun == "GoiasLUSIANA" ~ "luziania",
  state_mun == "Sao PauloLUISIANIA" ~ "luiziania",
  state_mun == "SergipeMACAMBRIA" ~ "macambira",
  state_mun == "PernambucoMACAPARAMA" ~ "macaparana",
  state_mun == "MaranhaoMAGELHAES DE ALMEIDA" ~ "magalhaes de almeida",
  state_mun == "SergipeMALHADOS" ~ "malhador",
  state_mun == "ParanaMANDAGUAPI" ~ "mandaguari",
  state_mun == "ParanaMANUEL RIBAS" ~ "manoel ribas",
  state_mun == "PernambucoMARAIA" ~ "maraial",
  state_mun == "Minas GeraisMARLIEIRA" ~ "marlieria",
  state_mun == "SergipeMAROIM" ~ "maruim",
  state_mun == "GoiasMARSAGAO" ~ "marzagao",
  state_mun == "AlagoasMATRIZ OE CAMARAGIBE" ~ "matriz de camaragibe",
  state_mun == "Sao PauloMEREDIANO" ~ "meridiano",
  state_mun == "Sao PauloMOCATUBA" ~ "macatuba",
  state_mun == "ParaMACAJUBA" ~ "mocajuba",
  state_mun == "GoiasMAIPORA" ~ "moipora",
  state_mun == "CearaMONENHOR TABOSA" ~ "monsenhor tabosa",
  state_mun == "MaranhaoMANTES ALTOS" ~ "montes altos",
  state_mun == "ParanaMUNHOZ DE MENO" ~ "munhoz de melo",
  state_mun == "Espirito SantoMUNIZ FREIRA" ~ "muniz freire",
  state_mun == "Sao PauloMURITINGA DO SUL" ~ "murutinga do sul",
  state_mun == "Rio de JaneiroNATIVIDADE DO CARANGOLA" ~ "natividade de carangola",
  state_mun == "Rio Grande do NorteNIZIA FLORESTA" ~ "nisia floresta",
  state_mun == "Sao PauloNOVA EROPA" ~ "nova europa",
  state_mun == "ParaNOVA TIMBOTOUA" ~ "nova timboteua",
  state_mun == "AmazonasARIPUANA" ~ "novo aripuana",
  state_mun == "Santa CatarinaORLEAES" ~ "orleans",
  state_mun == "Sao PauloOSCRA BRESSANE" ~ "oscar bressane",
  state_mun == "PiauiPALMERAIS" ~ "palmeirais",
  state_mun == "Sao PauloPARABUINA" ~ "paraibuna",
  state_mun == "Sao PauloPARANA PANEMA" ~ "paranapanema",
  state_mun == "PiauiPARANAGUA" ~ "parnagua",
  state_mun == "PernambucoPAU D'ALHO" ~ "paudalho",
  state_mun == "Sao PauloPEDREGUELHO" ~ "pedregulho",
  state_mun == "Sao PauloPEDREIDAS" ~ "pedreira",
  state_mun == "Minas GeraisPERDIÇÃO" ~ "perdigao",
  state_mun == "BahiaPI ATA" ~ "piata",
  state_mun == "GoiasPILAR OE  GOIAS" ~ "pilar de goias",
  state_mun == "MaranhaoPIRAMEMAS" ~ "pirapemas",
  state_mun == "Sao PauloPIRAPOSINHO" ~ "pirapozinho",
  state_mun == "Sao PauloPITANGUERIAS" ~ "pitangueiras",
  state_mun == "GoiasPLUM" ~ "pium",
  state_mun == "Minas GeraisPIUI" ~ "piumhi",
  state_mun == "Sao PauloPIANALTO" ~ "planalto",
  state_mun == "AlagoasPOLO DAS TR1NCHEIRAS" ~ "poco das trincheiras",
  state_mun == "Sao PauloPOLONIA" ~ "poloni",
  state_mun == "ParanaPOTENT('" ~ "porecatu",
  state_mun == "AlagoasQEBRANGULO" ~ "quebrangulo",
  state_mun == "Sao PauloREGENTE FEIJU" ~ "regente feijo",
  state_mun == "BahiaRIACHAO DO JACU1PE" ~ "riachao do jacuipe",
  state_mun == "BahiaRIACHO OE  SANTANA" ~ "riacho de santana",
  state_mun == "GoiasRIANOPOLIS" ~ "rianapolis",
  state_mun == "ParanaRIBERAO CLARO" ~ "ribeirao claro",
  state_mun == "PiauiREBEIRO GONCALVES" ~ "ribeiro goncalves",
  state_mun == "Sao PauloRIFANIA" ~ "rifaina",
  state_mun == "Santa CatarinaRIO D'OESTE" ~ "rio do oeste",
  state_mun == "GoiasRUPIATABA" ~ "rubiataba",
  state_mun == "Rio Grande do SulSAMANDUVA" ~ "sananduva",
  state_mun == "Sao PauloSANTA ADELINA" ~ "santa adelia",
  state_mun == "Sao PauloSANTA BARBARA DO OESTE" ~ "santa barbara d'oeste",
  state_mun == "ParanaSANTA CRUZ DO MONTE CASTELO" ~ "santa cruz de monte castelo",
  state_mun == "PernambucoSANTA CRUZ DO CAPRIBARIBE" ~ "santa cruz do capibaribe",
  state_mun == "SergipeSANTA LUZIA DO ITANHI" ~ "santa luzia do itanhy",
  state_mun == "Sao PauloSANTA MARIA DE SERRA" ~ "santa maria da serra",
  state_mun == "Sao PauloSANTA ROSA DO VITERBO" ~ "santa rosa de viterbo",
  state_mun == "Sao PauloSANTANA DO PARNAIBA" ~ "santana de parnaiba",
  state_mun == "Rio Grande do SulSANT'ANA DO LIVRAMENTO" ~ "santana do livramento",
  state_mun == "Rio Grande do NorteSANTANA DOS MATOS" ~ "santana do matos",
  state_mun == "Santa CatarinaSTO. AMARO DA IMPERATIZ" ~ "santo amaro da imperatriz",
  state_mun == "ParanaSANTO ANTONIO DE PLATINA" ~ "santo antonio da platina",
  state_mun == "Rio Grande do SulSANTO AGUSTO" ~ "santo augusto",
  state_mun == "Minas GeraisSAO DOMINGOS DA PRATA" ~ "sao domingos do prata",
  state_mun == "CearaSAOA JOAO DO JAGUARBIE" ~ "sao joao do jaguaribe",
  state_mun == "Sao PauloSAO JOAQUIM DO BARRA" ~ "sao joaquim da barra",
  state_mun == "Rio Grande do NorteSAO JOSE DE CAMPESTRE" ~ "sao jose do campestre",
  state_mun == "Santa CatarinaSAO LOURENCO D'OESTE" ~ "sao lourenco do oeste",
  state_mun == "GoiasSAO  LUIS  DE  MONIES  BELOS" ~ "sao luis de montes belos",
  state_mun == "Sao PauloSAO MANOEL" ~ "sao manuel",
  state_mun == "Santa CatarinaSAO MIGUEL D'OESTE" ~ "sao miguel do oeste",
  state_mun == "PiauiSAO MIGUEL DO TAPULO" ~ "sao miguel do tapuio",
  state_mun == "AmazonasSAO PAULO DO OLIVENC" ~ "sao paulo de olivenca",
  state_mun == "Rio de JaneiroSAO  PEDRO  D'ALDEIA" ~ "sao pedro da aldeia",
  state_mun == "MaranhaoSAO RAIMUNDO DAS MANGABELRAS" ~ "sao raimundo das mangabeiras",
  state_mun == "ParaSAO SEBASTIAO DA BO VISTA" ~ "sao sebastiao da boa vista",
  state_mun == "Sao PauloSAO SEBATIAO DA GRAMA" ~ "sao sebastiao da grama",
  state_mun == "Rio Grande do SulSAO SAPE" ~ "sao sepe",
  state_mun == "GoiasSAO  SINAO" ~ "sao simao",
  state_mun == "Rio Grande do SulSAPIRANBA" ~ "sapiranga",
  state_mun == "Rio de JaneiroSAGUAREMA" ~ "saquarema",
  state_mun == "Minas GeraisSENHOR DE OLIVEIRA" ~ "senhora de oliveira",
  state_mun == "Minas GeraisSENHORAS DOS REMEDIOS" ~ "senhora dos remedios",
  state_mun == "Rio Grande do NorteBBRRA CAIADA" ~ "serra caiada",
  state_mun == "ParaibaBARRA DA RAIZ" ~ "serra da raiz",
  state_mun == "GoiasSITIO DABADIA" ~ "sitio d'abadia",
  state_mun == "CearaSOMBRAL" ~ "sobral",
  state_mun == "Sao PauloSUD MENUCCI" ~ "sud mennucci",
  state_mun == "AmazonasTEPAUA" ~ "tapaua",
  state_mun == "Rio Grande do SulTAPEJANA" ~ "tapejara",
  state_mun == "Sao PauloTAQUATARITUBA" ~ "taquarituba",
  state_mun == "SergipeTOMAR DE GERU" ~ "tomar do geru",
  state_mun == "Rio Grande do SulTRES DE MAJO" ~ "tres de maio",
  state_mun == "Sao PauloTRES FE DO SUL" ~ "tres fronteiras",
  state_mun == "Rio Grande do SulTERS PASSOS" ~ "tres passos",
  state_mun == "Rio Grande do SulTUPANEIRETA" ~ "tupancireta",
  state_mun == "GoiasTOPIRATINS" ~ "tupiratins",
  state_mun == "MaranhaoTURIASSU" ~ "turiacu",
  state_mun == "MaranhaoTUTOI" ~ "tutoia",
  state_mun == "AmazonasWALPES" ~ "uaupes",
  state_mun == "Sao PauloUBIRAJA" ~ "ubirajara",
  state_mun == "ParanaUNIAO DE VITORIA" ~ "uniao da vitoria",
  state_mun == "GoiasURACU" ~ "uruacu",
  state_mun == "AmazonasURACARA" ~ "urucara",
  state_mun == "BahiaJANDAIRA" ~ "jandaira",
  state_mun == "Sao PauloVELENTIM GENTIL" ~ "valentim gentil",
  state_mun == "ParanaVENCESLAU BRAS" ~ "wenceslau braz",
  state_mun == "GoiasXAMOIOA" ~ "xambioa",
  state_mun == "Rio Grande do NorteATONES BEZERRA" ~ "afonso bezerra",
  state_mun == "GoiasANORINOPOLIS" ~ "amorinopolis",
  state_mun == "BahiaCANAVIEIRA" ~ "canavieiras",
  state_mun == "Espirito SantoCONEEICIE DA BARRA" ~ "conceicao da barra",
  state_mun == "Sao PauloGUICARA" ~ "guaicara",
  state_mun == "SergipeLARANJERIAS" ~ "laranjeiras",
  state_mun == "Santa CatarinaLEBOA REGIS" ~ "lebon regis",
  state_mun == "AlagoasMAJOR IZIDRO" ~ "major isidoro",
  state_mun == "Rio de JaneiroCONEEICAO DO MACABU" ~ "conceicao de macabu",
  state_mun == "GoiasJANDOIA" ~ 'jandaia',
  state_mun == "Sao PauloMOGI DA CRUZES" ~ 'mogi das cruzes',
  TRUE ~ name_mun)) %>%
  group_by(state) %>%
  distinct(name_mun, .keep_all = T) %>%
  ungroup() %>%
  mutate(pres1960_validVotes = pres1960_votes_janio + pres1960_votes_barros + pres1960_votes_lott,
         vicepres1960_validVotes = vicepres1960_votes_ferrari + vicepres1960_votes_goulart + vicepres1960_votes_campos) %>%
  mutate(across(.cols = starts_with("pres1960_votes_"),
                .fns = ~./pres1960_validVotes,
                .names = "{col}_share" ))  %>%
  mutate(across(.cols = starts_with("vicepres1960_votes_"),
                .fns = ~./vicepres1960_validVotes,
                .names = "{col}_share" )) %>%
  mutate(uf_1970 = case_when(state == 'Alagoas' ~ "AL",
                              state == 'Amazonas' ~ 'AM',
                              state == 'Bahia' ~ 'BA',
                              state == 'Ceara' ~ 'CE',
                              state == 'Espirito Santo' ~ 'ES',
                              state == 'Goias' ~ 'GO',
                              state == 'Maranhao' ~ 'MA',
                              state == 'Mato Grosso' ~ 'MT',
                              state == 'Minas Gerais' ~ 'MG',
                              state == 'Para' ~ 'PA',
                              state == 'Paraiba' ~ 'PB',
                              state == 'Parana' ~ 'PR',
                              state == 'Pernambuco' ~ 'PE',
                              state == 'Piaui' ~ 'PI',
                              state == 'Rio de Janeiro' ~ 'RJ',
                              state == 'Rio Grande do Norte' ~ 'RN',
                              state == 'Rio Grande do Sul' ~ 'RS',
                              state == 'Santa Catarina' ~ 'SC',
                              state == 'Sao Paulo' ~ 'SP',
                              state == 'Sergipe' ~ 'SE')) %>%
  relocate(uf_1970) %>%
  rename(name_mun_1960 = name_mun)

pres_el1960 <- pres_el1960 %>% inner_join(appmayors::crosswalk_1960_1970, by = c("uf_1970", "name_mun_1960")) %>%
  relocate(uf_2010) %>%
  relocate(cod_mun_ibge, name_mun_1970, .before = name_mun_1960)

usethis::use_data(pres_el1960, overwrite = TRUE)
